services:
  - type: web
    name: brest-id-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "*" # Замените на конкретные домены в продакшене

databases:
  - name: brestid-db
    plan: free
    databaseName: brestid
    user: brestid_user